# Generated by Django 2.2.12 on 2020-06-07 13:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='地區名稱')),
                ('foreign', models.BooleanField(default=False, verbose_name='國外')),
                ('filter', models.CharField(max_length=20, verbose_name='過濾器')),
                ('sort_index', models.IntegerField(default=0, verbose_name='排序(整數)')),
            ],
            options={
                'verbose_name': '行程地區',
                'verbose_name_plural': '行程地區',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('departure_date', models.DateField(verbose_name='出團日期')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='內容')),
                ('category', models.ForeignKey(on_delete=False, to='tour.Area', verbose_name='地區')),
            ],
            options={
                'verbose_name': '行程',
                'verbose_name_plural': '行程',
            },
        ),
    ]
