# Generated by Django 2.2.13 on 2020-06-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='departure_date',
        ),
        migrations.AddField(
            model_name='tour',
            name='days',
            field=models.IntegerField(blank=True, null=True, verbose_name='天數'),
        ),
        migrations.AddField(
            model_name='tour',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='圖片1'),
        ),
        migrations.AddField(
            model_name='tour',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='圖片2'),
        ),
    ]
