# Generated by Django 2.2.13 on 2020-06-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_auto_20200608_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasontour',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='隱藏'),
        ),
        migrations.AddField(
            model_name='tour',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='隱藏'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='tour.Area', verbose_name='地區'),
        ),
    ]
