# Generated by Django 2.2.15 on 2020-09-07 22:38

from django.db import migrations, models
import tour.models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_auto_20200609_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='filter',
            field=models.CharField(default=tour.models.generate_random_code, max_length=20, unique=True, verbose_name='過濾器'),
        ),
    ]
