# Generated by Django 2.2.15 on 2020-09-28 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('email', models.CharField(max_length=255, verbose_name='電子郵件')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('subject', models.CharField(max_length=100, verbose_name='主旨')),
                ('content', models.TextField(verbose_name='內容')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='時間戳')),
            ],
            options={
                'verbose_name': '訊息',
                'verbose_name_plural': '訊息',
            },
        ),
    ]
