# Generated by Django 2.2.15 on 2021-09-29 14:05

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('description', models.TextField(verbose_name='敘述')),
                ('photo', models.ImageField(upload_to='', verbose_name='圖片')),
                ('crop_photo', image_cropping.fields.ImageRatioField('photo1', '320x180', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='剪裁圖片')),
            ],
            options={
                'verbose_name': '行程組件',
                'verbose_name_plural': '行程組件',
            },
        ),
    ]
