# Generated by Django 2.2.13 on 2020-08-07 16:34

import album.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('travel_date', models.DateField(default=django.utils.timezone.now, verbose_name='出團日期')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('random_code', models.UUIDField(default=uuid.uuid4, verbose_name='隨機碼')),
            ],
            options={
                'verbose_name': '相簿',
                'verbose_name_plural': '相簿',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=album.models.upload_to_album, verbose_name='照片')),
                ('upload_date', models.DateTimeField(blank=True, verbose_name='上傳日期')),
                ('shooting_date', models.DateTimeField(blank=True, null=True, verbose_name='拍攝日期')),
                ('cover_photo', models.BooleanField(default=False, verbose_name='相簿封面')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='album.Album', verbose_name='相簿')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='album.Company', verbose_name='公司'),
        ),
    ]
