# Generated by Django 2.2.13 on 2020-08-10 16:43

import album.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='random_code',
            field=models.CharField(default=album.models.generate_random_code, max_length=10, unique=True, verbose_name='隨機碼'),
        ),
    ]
